---
abstract: Hadouken
author:
  - 'dek <dek@dek.bz>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Hadouken
name: Hadouken
no_index:
  directory:
    - inc
    - t
requires:
  Any::Moose: 0
  AnyEvent: 0
  AnyEvent::DNS: 0
  AnyEvent::Whois::Raw: 0
  Config::General: 0
  Convert::PEM: 0
  Crypt::Blowfish_PP: 0
  Crypt::CBC: 0
  Crypt::OpenSSL::RSA: 0
  Crypt::RSA: 0
  Crypt::Random: 0
  Cwd: 0
  Daemon::Control: 0
  Data::Dumper: 0
  Data::Printer: 0
  Digest::SHA: 0
  Digest::SHA3: 0
  Encode: 0
  File::Basename: 0
  File::Spec: 0
  FindBin: 0
  Geo::IP: 0
  HTML::Strip: 0
  HTML::TokeParser: 0
  HTTP::Cookies: 0
  JSON: 0
  JSON::XS: 0
  LWP::ConnCache: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  MIME::Base64: 0
  Module::Pluggable: 0
  Moose: 0
  MooseX::Getopt::GLD: 0
  Net::Whois::IP: 0
  Object::Event: 0
  POSIX: 0
  REST::Google: 0
  Regexp::Assemble: 0
  Regexp::Common: 0
  Scalar::Util: 0
  String::IRC: 0
  Term::ReadPassword: 0
  Text::CSV_XS: 0
  Text::Unidecode: 0
  Tie::Array::CSV: 0
  Time::Elapsed: 0
  Time::HiRes: 0
  TryCatch: 0
  URI: 0
  URI::Escape: 0
  Yahoo::Weather: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.8.6
